//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursova.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string NameProduct { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> idCategory { get; set; }
    
        public virtual Gategory Gategory { get; set; }
    }
}
