//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursova.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvededService
    {
        public int id { get; set; }
        public Nullable<int> idService { get; set; }
        public Nullable<int> idEmployees { get; set; }
        public Nullable<int> idClient { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Service Service { get; set; }
    }
}
